version: '2'
services:
  web:
    build: .
    volumes:
     - ".:/app"
    ports:
     - "9000:9000"
    environment:
     - COOKIE_SECRET=secretme
  db:
    image: postgres:9.5
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
